version: '3.1'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USERNAME=
      - MONGO_PASSWORD=

  mongo:
    image: mongo:5.0.3
    ports:
      - "27017:27017"
    
